version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: realestate-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
      - type: bind
        source: ./mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: ["--bind_ip_all", "--wiredTigerCacheSizeGB", "1.5"]
    stop_grace_period: 30s
    stop_signal: SIGINT
    networks:
      - realestate-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: realestate-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/realestate?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      mongodb:
        condition: service_healthy
    stop_grace_period: 20s
    stop_signal: SIGTERM
    networks:
      - realestate-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    container_name: realestate-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - WDS_SOCKET_PORT=0
      - BROWSER=none
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      backend:
        condition: service_healthy
    stop_grace_period: 20s
    stop_signal: SIGTERM
    networks:
      - realestate-network

networks:
  realestate-network:
    driver: bridge
    name: realestate-network

volumes:
  mongodb_data:
    driver: local 